# Generated by Django 6.0.3 on 2026-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Who Are We', help_text='Small label above the heading', max_length=100)),
                ('section_label_en', models.CharField(default='Who Are We', help_text='Small label above the heading', max_length=100, null=True)),
                ('section_label_tr', models.CharField(default='Who Are We', help_text='Small label above the heading', max_length=100, null=True)),
                ('section_label_ru', models.CharField(default='Who Are We', help_text='Small label above the heading', max_length=100, null=True)),
                ('heading', models.CharField(default='We Make Dreams Come True', help_text='Main heading for the section', max_length=200)),
                ('heading_en', models.CharField(default='We Make Dreams Come True', help_text='Main heading for the section', max_length=200, null=True)),
                ('heading_tr', models.CharField(default='We Make Dreams Come True', help_text='Main heading for the section', max_length=200, null=True)),
                ('heading_ru', models.CharField(default='We Make Dreams Come True', help_text='Main heading for the section', max_length=200, null=True)),
                ('description', models.TextField(help_text='Description text about the company')),
                ('description_en', models.TextField(help_text='Description text about the company', null=True)),
                ('description_tr', models.TextField(help_text='Description text about the company', null=True)),
                ('description_ru', models.TextField(help_text='Description text about the company', null=True)),
                ('image', models.ImageField(help_text='Image for the about section', upload_to='about/')),
                ('stat1_number', models.CharField(default='150+', help_text='First statistic number (e.g., 150+)', max_length=20)),
                ('stat1_label', models.CharField(default='Destinations', help_text='Label for first statistic', max_length=100)),
                ('stat1_label_en', models.CharField(default='Destinations', help_text='Label for first statistic', max_length=100, null=True)),
                ('stat1_label_tr', models.CharField(default='Destinations', help_text='Label for first statistic', max_length=100, null=True)),
                ('stat1_label_ru', models.CharField(default='Destinations', help_text='Label for first statistic', max_length=100, null=True)),
                ('stat2_number', models.CharField(default='20K+', help_text='Second statistic number (e.g., 20K+)', max_length=20)),
                ('stat2_label', models.CharField(default='Happy Clients', help_text='Label for second statistic', max_length=100)),
                ('stat2_label_en', models.CharField(default='Happy Clients', help_text='Label for second statistic', max_length=100, null=True)),
                ('stat2_label_tr', models.CharField(default='Happy Clients', help_text='Label for second statistic', max_length=100, null=True)),
                ('stat2_label_ru', models.CharField(default='Happy Clients', help_text='Label for second statistic', max_length=100, null=True)),
                ('stat3_number', models.CharField(default='98%', help_text='Third statistic number (e.g., 98%)', max_length=20)),
                ('stat3_label', models.CharField(default='Satisfaction', help_text='Label for third statistic', max_length=100)),
                ('stat3_label_en', models.CharField(default='Satisfaction', help_text='Label for third statistic', max_length=100, null=True)),
                ('stat3_label_tr', models.CharField(default='Satisfaction', help_text='Label for third statistic', max_length=100, null=True)),
                ('stat3_label_ru', models.CharField(default='Satisfaction', help_text='Label for third statistic', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one section should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
