# Generated by Django 6.0.3 on 2026-03-27 23:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Accessibility Option',
                'verbose_name_plural': 'Accessibility Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, help_text='ISO language code (e.g., en, es, fr)', max_length=10)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Short catchy description', max_length=300)),
                ('short_description', models.TextField(help_text='Brief overview for listings', max_length=500)),
                ('description', models.TextField(help_text='Full detailed description (supports HTML)')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Duration in hours')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Additional minutes (0-59)', validators=[django.core.validators.MaxValueValidator(59)])),
                ('duration_text', models.CharField(blank=True, help_text="Optional custom duration display (e.g., '2 days, 1 night')", max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult')], default='easy', max_length=20)),
                ('experience_type', models.CharField(choices=[('group', 'Group Tour'), ('private', 'Private Tour'), ('semi_private', 'Semi-Private Tour'), ('self_guided', 'Self-Guided')], default='group', max_length=20)),
                ('pickup_information', models.TextField(blank=True, help_text='Details about pickup locations, times, and procedures')),
                ('itinerary_description', models.TextField(blank=True, help_text='General itinerary overview (detailed items can be added separately)')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants per booking (leave blank for unlimited)', null=True)),
                ('min_participants', models.PositiveIntegerField(default=1, help_text='Minimum number of participants required')),
                ('booking_cutoff_hours', models.PositiveIntegerField(default=24, help_text='How many hours in advance booking must be made')),
                ('instant_confirmation', models.BooleanField(default=True, help_text='Whether booking is instantly confirmed')),
                ('review_count', models.PositiveIntegerField(default=0, editable=False)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Is tour available for booking?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage?')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('accessibility_options', models.ManyToManyField(blank=True, related_name='tours', to='tours.accessibilityoption')),
                ('languages', models.ManyToManyField(blank=True, related_name='tours', to='tours.language')),
                ('categories', models.ManyToManyField(blank=True, related_name='tours', to='tours.tourcategory')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this pickup point')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/main pickup location')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Pickup Location',
                'verbose_name_plural': 'Pickup Locations',
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('time', models.CharField(blank=True, help_text="Time or duration for this step (e.g., '09:00 AM' or '2 hours')", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ItemToBring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False, help_text='Is this item required or recommended?')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_to_bring', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Item to Bring',
                'verbose_name_plural': 'Items to Bring',
                'ordering': ['-is_required', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Included Item',
                'verbose_name_plural': 'Included Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Excluded Item',
                'verbose_name_plural': 'Excluded Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.PositiveIntegerField(help_text="Hours before tour start (e.g., 24 for '24 hours before')")),
                ('refund_percentage', models.PositiveIntegerField(help_text='Percentage of refund (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(blank=True, help_text='Optional custom description of this rule', max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_rules', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Cancellation Policy Rule',
                'verbose_name_plural': 'Cancellation Policy Rules',
                'ordering': ['-hours_before', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Main image displayed in listings and at top of detail page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Image',
                'verbose_name_plural': 'Tour Images',
                'ordering': ['-is_main', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TourNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('restriction', 'Restriction'), ('accessibility', 'Accessibility Note'), ('weather', 'Weather Condition'), ('important', 'Important')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Note',
                'verbose_name_plural': 'Tour Notes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='Optional start time', null=True)),
                ('slots_available', models.PositiveIntegerField(blank=True, help_text='Maximum bookings for this date (leave blank for unlimited)', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='Special notes for this date', max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Availability',
                'verbose_name_plural': 'Tour Availabilities',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['tour', 'date', 'is_available'], name='tours_toura_tour_id_e8a802_idx')],
                'unique_together': {('tour', 'date', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tours_tour_slug_a32940_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', 'is_featured'], name='tours_tour_is_acti_1b8fef_idx'),
        ),
    ]
