# Generated by Django 6.0.3 on 2026-03-29 02:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_tr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_tr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('title_en', models.CharField(help_text='Post title', max_length=200, null=True)),
                ('title_tr', models.CharField(help_text='Post title', max_length=200, null=True)),
                ('title_ru', models.CharField(help_text='Post title', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the post', null=True, upload_to='blog/posts/%Y/%m/')),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary of the post', max_length=500)),
                ('excerpt_en', models.TextField(blank=True, help_text='Short description/summary of the post', max_length=500, null=True)),
                ('excerpt_tr', models.TextField(blank=True, help_text='Short description/summary of the post', max_length=500, null=True)),
                ('excerpt_ru', models.TextField(blank=True, help_text='Short description/summary of the post', max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Main content (supports rich text editing)')),
                ('content_en', ckeditor.fields.RichTextField(help_text='Main content (supports rich text editing)', null=True)),
                ('content_tr', ckeditor.fields.RichTextField(help_text='Main content (supports rich text editing)', null=True)),
                ('content_ru', ckeditor.fields.RichTextField(help_text='Main content (supports rich text editing)', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., travel, europe, adventure)', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on homepage or listings')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the post should be published', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (leave blank to use post title)', max_length=60)),
                ('meta_title_en', models.CharField(blank=True, help_text='SEO title (leave blank to use post title)', max_length=60, null=True)),
                ('meta_title_tr', models.CharField(blank=True, help_text='SEO title (leave blank to use post title)', max_length=60, null=True)),
                ('meta_title_ru', models.CharField(blank=True, help_text='SEO title (leave blank to use post title)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (recommended 150-160 characters)', max_length=160)),
                ('meta_description_en', models.CharField(blank=True, help_text='SEO meta description (recommended 150-160 characters)', max_length=160, null=True)),
                ('meta_description_tr', models.CharField(blank=True, help_text='SEO meta description (recommended 150-160 characters)', max_length=160, null=True)),
                ('meta_description_ru', models.CharField(blank=True, help_text='SEO meta description (recommended 150-160 characters)', max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255)),
                ('meta_keywords_en', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255, null=True)),
                ('meta_keywords_tr', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255, null=True)),
                ('meta_keywords_ru', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from default')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title or post title)', max_length=60)),
                ('og_title_en', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title or post title)', max_length=60, null=True)),
                ('og_title_tr', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title or post title)', max_length=60, null=True)),
                ('og_title_ru', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title or post title)', max_length=60, null=True)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description', max_length=200)),
                ('og_description_en', models.CharField(blank=True, help_text='Open Graph description', max_length=200, null=True)),
                ('og_description_tr', models.CharField(blank=True, help_text='Open Graph description', max_length=200, null=True)),
                ('og_description_ru', models.CharField(blank=True, help_text='Open Graph description', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (leave blank to use featured image)', null=True, upload_to='blog/og_images/%Y/%m/')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'BlogPosting'), ('NewsArticle', 'NewsArticle')], default='BlogPosting', help_text='Schema.org type for structured data', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_post_publish_2c9212_idx'), models.Index(fields=['status'], name='blog_post_status_02ce19_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
        ),
    ]
